/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kotcrab_vne_win_thumbnails_WinThumbnailProvider */

#ifndef _Included_com_kotcrab_vne_win_thumbnails_WinThumbnailProvider
#define _Included_com_kotcrab_vne_win_thumbnails_WinThumbnailProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kotcrab_vne_win_thumbnails_WinThumbnailProvider
 * Method:    initJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kotcrab_vne_win_thumbnails_WinThumbnailProvider_initJni
  (JNIEnv *, jobject);

/*
 * Class:     com_kotcrab_vne_win_thumbnails_WinThumbnailProvider
 * Method:    getThumbnailJni
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_kotcrab_vne_win_thumbnails_WinThumbnailProvider_getThumbnailJni
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_kotcrab_vne_win_thumbnails_WinThumbnailProvider
 * Method:    disposeJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kotcrab_vne_win_thumbnails_WinThumbnailProvider_disposeJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
